### ISSUE TITLE
Provide a link to packages for people who don't want the whole image

### ISSUE THREAD

**Issue by xobs** [im-tomu/fomu-pi-gen#7]
We should link to the Debian packages themselves, for users who already have a working Raspberry Pi installation and just want to get to work.

**Comment by ewenmcneill** [comment]
This would also be useful for handling upgrades.  (I've just done the tar-home-dir, rewrite-sd-card, untar-home-dir upgrade from 1.2.6 to 1.2.7 (which worked fine, and `--placer heap` does seem to work), but it'd be even easier to be able to, eg, remount / rw and then `apt-get update && apt-get dist-upgrade`.)

Ewen

**Comment by xobs** [comment]
There is now a repo, as of v1.2.8.  More information at https://repo.fomu.im/

**Comment by ewenmcneill** [comment]
Thanks, that's very useful. 

A couple of quick notes:

*   The `apt-key` command should be `sudo apt-key ...`, ie:

    ```
    wget -O - https://repo.fomu.im/tomu-signing-key.asc | sudo apt-key add -
    ```

*   For our specific use case, it might be worth suggesting to users:

    ```
    sudo mount -o remount,rw /
    ```

    before trying to do those steps, otherwise it probably won't work for them.

Ewen

With a 1.2.8 base image it seems to just work, although obviously there aren't any packages in the https://repo.fomu.im/ package index which aren't already in the 1.2.8 image :-)

```
fomu@fomu-dev:~ $ sudo mount -o remount,rw /
fomu@fomu-dev:~ $ grep -v "^#" /etc/apt/sources.list.d/*
/etc/apt/sources.list.d/fomu.list:deb https://repo.fomu.im/debian/ stretch main
/etc/apt/sources.list.d/raspi.list:deb http://archive.raspberrypi.org/debian/ stretch main ui
fomu@fomu-dev:~ $ sudo mount -o remount,rw /
fomu@fomu-dev:~ $ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease    
Get:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15.0 kB]     
Hit:3 https://repo.fomu.im/debian stretch InRelease
Fetched 15.0 kB in 3s (4,264 B/s)
Reading package lists... Done
fomu@fomu-dev:~ $ sudo apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
fomu@fomu-dev:~ $ sudo mount -o remount,ro /
fomu@fomu-dev:~ $ 
```

**Comment by xobs** [comment]
I've updated the README to reflect those suggestions.  Thanks!
