### ISSUE TITLE
Release 1.2.1

### ISSUE THREAD

**Issue by ewenmcneill** [im-tomu/fomu-pi-gen#8]
Hi @xobs, 

Re your comment on IRC a few days back that the only reason you'd not made the [1.2.1 release](https://github.com/im-tomu/fomu-pi-gen/releases/tag/v1.2.1-fomu) the latest release was that you hadn't tested it.

I've downloaded it, and copied it onto my SD card, and booted it, and it seems to work for me to the same extent that 1.2 did, eg, can follow the instructions to get a "blink" example built/loaded.  So probably working okay I think.  Maybe make it an official release at this point, since it's all a bit "preview" anyway :-)

1.2.1 does have the RISC-V toolchain package installed:

```
fomu@fomu-dev:/tmp $ dpkg -l | grep risc
ii  riscv-toolchain                      8.2.0-before-fsf-gdb-2-g411d134                armhf        riscv toolchain packaged for Fomu
fomu@fomu-dev:/tmp $ 
```

Also by way of suggestions, it might help to either (a) do as part of the build or (b) suggest at https://tomu.im/fomu-evt3/ that people do something like:

```
sudo mkdir -p /home/var/lib/sudo
sudo mount -o remount,rw /
sudo sh -c 'rm -r /var/lib/sudo && ln -s /home/var/lib/sudo /var/lib/sudo'
sudo mount -o remount,ro /
```

to give `sudo` a writeable directory to keep its state.  That seems to work for me, with the caveat that the "rm -r" and "ln -s" need to be in a single `sudo` run otherwise the directory will be recreated...

That reduces the need to type the `fomu` password in repeatedly, and/or getting a mix of warnings about read only file systems and stale information (if it gets written when the filesystem is mounted read write to change something).

Ewen

**Comment by xobs** [comment]
I'm building v1.2.2-fomu now that adds a patch to fix the `sudo` issue.  Thanks for the report and the fix!

Additionally, v1.2.2 should fix a bug with `htpdate` and add an experimental lm32 compiler.

I'll close this issue once it's released.

**Comment by xobs** [comment]
v1.2.2 has been released, which fixes the `sudo` issue.  There is still a small issue with `htpdate`, which I'm fixing now and will release shortly.

**Comment by ewenmcneill** [comment]
Thanks for the `sudo` fix, it seems to work for me without any local workarounds now:

```
fomu@fomu-dev:~/src/fomu-tests/blink $ sudo ls
[sudo] password for fomu: 
blink.bin  blink.v  Makefile
fomu@fomu-dev:~/src/fomu-tests/blink $ sudo ls
blink.bin  blink.v  Makefile
fomu@fomu-dev:~/src/fomu-tests/blink $ 
```

And 1.2.2 works once I [manually set the date](https://github.com/im-tomu/fomu-pi-gen/issues/1#issuecomment-474712803), which it looks like you've got a work around for in https://github.com/im-tomu/fomu-pi-gen/issues/1#issuecomment-473677969 already, so hopefully fixed in the next filesystem build.

Also looks like `riscv-toolchain` and `lm32-toolchain` are installed as intended:

```
fomu@fomu-dev:~/src/fomu-tests/blink $ dpkg -l | grep risc
ii  riscv-toolchain                      8.2.0-before-fsf-gdb-2-g411d134                armhf        riscv toolchain packaged for Fomu
fomu@fomu-dev:~/src/fomu-tests/blink $ dpkg -l | grep lm32
ii  lm32-toolchain                       8.3.0-fomu                                     armhf        lm32 toolchain packaged for Fomu
fomu@fomu-dev:~/src/fomu-tests/blink $ 
fomu@fomu-dev:~/src/fomu-tests/blink $ dpkg -L riscv-toolchain | wc -l
1602
fomu@fomu-dev:~/src/fomu-tests/blink $ dpkg -L lm32-toolchain | wc -l
942
fomu@fomu-dev:~/src/fomu-tests/blink $ 
```

Thanks for the update / heads up,

Ewen
